# This is a basic workflow to help you get started with Actions

name: Flowdock Poster

on:
  pull_request:
    types: [opened]

jobs:
  post-it:
    runs-on: ubuntu-latest
    name: Posts the PR to flowdock

    steps:
      - name: Post action
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'AJ :)'
