name: Teams Poster (External Actions)
on:
  pull_request:
    types: [opened, ready_for_review]
jobs:
  post-it:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    name: Posts the PR to a Teams webhook

    steps:
      - name: Post PR to Teams
        uses: n-kerns/action-teams-poster@master
        with:
          webhook_url: ${{ secrets.TEAMS_WEBHOOK_URL }}
