# This is a basic workflow to help you get started with Actions

name: Flowdock Poster

on:
  pull_request:
    types: [created]

jobs:
  post-it:
    runs-on: ubuntu-latest
    name: Posts the PR to flowdock

    steps:
      - name: Post action
        uses: n-kerns/TestingActions@v1.1
        with:
          organization: 'techsmith'
          flow: 'cory-test'
          flowdock_api_token: ${{ secrets.FLOWDOCK_API_KEY }}

